# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'TakeGive'
  
  app.device_family = [:iphone, :ipad]
  app.frameworks << "QuartzCore"
  app.frameworks << "MapKit"
  app.frameworks << "CoreLocation"
  
  app.info_plist['NSLocationWhenInUseUsageDescription'] = 'Shows you items around you.'
  
end
